version: '3.4'

services:
  invoice-challenge:
    build: .
    ports:
    - "5000:5000"
    volumes:
      - .:/usr/src/app
    links:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: "3306"
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      SECREAT_KEY: ${SECREAT_KEY}
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
