version: '3.4'

services:
  invoice-challenge:
    build: .
    ports:
    - "5000:80"
    volumes:
      - .:/usr/src/app
    links:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: "3306"
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro